"""
TypedDict-based state object for LangGraph workflow.
"""

from typing import Any, TypedDict

import pandas as pd

from .data import DatasetMetadata
from .summary import SummaryResult
from .training import TrainExecutionResult


class WorkflowState(TypedDict, total=False):
    """
    State object passed between LangGraph nodes during automatic model build.

    Fields:
        df: pandas DataFrame containing the dataset.
        metadata: Dataset metadata.
        target_column: Name of the target column for training.
        summary_result: SummaryResult object returned by summary_chain.
        training_result: TrainExecutionResult returned by training_chain.
        retry_count: Number of retry attempts for the current node.
        summary_errors: List of errors encountered during summarization.
        training_errors: List of errors encountered during training.
        status: "ok" or "failed" for the last node execution.
        previous_code: Previously failed training code (used in fix_error_training_chain).
        previous_errors: List of error messages from previous executions.
        fixed_code: Code generated by fix_error_training_chain after fixing errors.
        use_fixed_summary: Whether to use a fixed summary for training (boolean flag).
        llm: Optional LLM client instance used for generating code or summaries.
    """

    df: pd.DataFrame
    metadata: DatasetMetadata
    target_column: str
    summary_result: SummaryResult | None
    training_result: TrainExecutionResult | None
    retry_count: int
    summary_errors: list[str]
    training_errors: list[str]
    status: str  # "ok" or "failed"
    previous_code: str | None
    fixed_code: str | None
    use_fixed_summary: bool
    llm: Any | None
